## 0. ИМПОРТ НЕОБХОДИМЫХ ФАЙЛОВ

In [ ]:
import pandas as pd
import numpy as np

import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

## 2. ДАННЫЕ ЦИАН

### 2.1 ПЕРВИЧНЫЙ ПРОСМОРТ

#### 2.1.1 ПЕРЕСОХРАНЕНИЕ В ФОРМАТЕ .csv

In [ ]:
new_building = pd.read_excel('new_building_02102024.xlsx')
new_building.to_csv('new_building_02102024.csv', index=False)

In [ ]:
# Выгрузка .csv (МСК)
new_building = pd.read_csv('new_building_02102024.csv')

In [ ]:
new_building.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11957 entries, 0 to 11956
Data columns (total 74 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ID К                                     11957 non-null  int64
 1   ID ЖК                                    11957 non-null  int64
 2   ЖК рус                                   11957 non-null  object
 3   ЖК англ                                  3323 non-null   object
 4   Корпус                                   11957 non-null  object
 5   кр Корпус                                11948 non-null  object
 6   Адрес корп                               11957 non-null  object
 7   lat                                      11957 non-null  float64
 8   lng                                      11957 non-null  float64
 9   Район Город                              11957 non-null  object
 10  Округ Направление                        11957 non-null  object
 11  Регион                                   11957 non-null  object
 12  АТД                                      11957 non-null  object
 13  Метро                                    11563 non-null  object
 14  Станция жд                               4474 non-null   object
 15  Застройщик ЖК                            11957 non-null  object
 16  Этажность К мин                          11957 non-null  int64
 17  Этажность К макс                         11957 non-null  int64
 18  Площадь К                                11957 non-null  int64
 19  Квартир в К                              11957 non-null  int64
 20  1к кв                                    11957 non-null  int64
 21  2к кв                                    11957 non-null  int64
 22  3к кв                                    11957 non-null  int64
 23  4к кв                                    11957 non-null  int64
 24  Тип помещений                            11957 non-null  object
 25  Стены в К                                11957 non-null  object
 26  Сдача К                                  11955 non-null  object
 27  Стадия К                                 11957 non-null  object
 28  Старт продаж К                           10897 non-null  float64
 29  Договор К                                11957 non-null  object
 30  Валюта цены в К                          9913 non-null   object
 31  Класс К                                  11957 non-null  object
 32  до МКАД                                  11957 non-null  float64
 33  внутри                                   11957 non-null  int64
 34  Отделка                                  11956 non-null  object
 35  Зона                                     11957 non-null  object
 36  Очередь                                  10341 non-null  object
 37  РВЭ                                      4824 non-null   object
 38  ст                                       1911 non-null   float64
 39  Метро транспортом                        11957 non-null  int64
 40  Метро пешком                             11957 non-null  int64
 41  Высота потолков                          7433 non-null   object
 42  Продано кв и ап розн                     11957 non-null  int64
 43  Остатки кв и ап в розн                   11957 non-null  int64
 44  % остатков в лотах                       11957 non-null  float64
 45  Кв и ап. в прайсах                       11957 non-null  int64
 46  % расп. корпусов                         11957 non-null  float64
 47  Участок                                  10819 non-null  object
 48  Продано кв и ап розн кв. м               11957 non-null  int64
 49  Остатки кв и ап в розн кв. м             11957 non-null  int64
 50  % остатков в кв. м                       11957 non-null  float64
 51  Продажи кв и ап розн в месяц кв. м       11957 non-null  float64
 52  Продажи кв и ап розн в месяц             11957 non-null  float64
 53  мес. для продажи                         11957 non-null  float64
 54  мес. до сдачи                            11957 non-null  int64
 55  срок экспозиции, мес                     11957 non-null  int64
 56  изменение ср. цены кв. м                 11957 non-null  float64
 57  среднемес рост цен                       11957 non-null  float64
 58  номер ПД и объекта                       7058 non-null   object
 59  ID дом.рф                                6507 non-null   float64
 60  Ключи (д)                                4768 non-null   object
 61  Дата РВЭ (д)                             4127 non-null   object
 62  м/м на придомовой территории (д)         3855 non-null   float64
 63  м/м вне придомовой территории (д)        2194 non-null   float64
 64  м/м в паркинге (д)                       2627 non-null   float64
 65  пассажирских лифтов (д)                  3557 non-null   float64
 66  грузовых лифтов (д)                      2000 non-null   float64
 67  квартир на площадке (д)                  5580 non-null   float64
 68  подъездов (д)                            5580 non-null   float64
 69  корпусов в объекте                       6499 non-null   float64
 70  Общая площадь (д)                        3156 non-null   float64
 71  Планируемая стоимость строительства (д)  3227 non-null   float64
 72  Банк эскроу (д)                          2676 non-null   object
 73  Банк кредитор (д)                        2676 non-null   object
dtypes: float64(24), int64(20), object(30)
memory usage: 6.8+ MB

In [ ]:
new_building.describe()

,ID К,ID ЖК,lat,lng,Этажность К мин,Этажность К макс,Площадь К,Квартир в К,1к кв,2к кв,...,м/м на придомовой территории (д),м/м вне придомовой территории (д),м/м в паркинге (д),пассажирских лифтов (д),грузовых лифтов (д),квартир на площадке (д),подъездов (д),корпусов в объекте,Общая площадь (д),Планируемая стоимость строительства (д)
count,11957.000,11957.000,11957.000,11957.000,11957.000,11957.000,11957.000,11957.000,11957.000,11957.000,...,3855.000,2194.000,2627.000,3557.000,2000.000,5580.000,5580.000,6499.000,3156.000,3227.000
mean,9592.931,2905.955,55.732,37.559,13.580,14.537,12090.889,225.899,109.004,78.945,...,48.669,74.464,158.814,4.407,3.474,8.069,3.210,1.918,15451.784,2579626942.923
std,5122.362,2092.315,0.212,0.361,9.448,9.766,12147.762,235.125,139.179,92.537,...,71.319,122.589,178.119,4.387,3.086,12.498,2.985,1.886,14546.666,3258897130.117
min,1411.000,529.000,54.762,30.290,0.000,0.000,0.000,0.000,0.000,0.000,...,0.300,0.200,9.500,0.300,0.100,1.000,0.200,1.000,90.000,189000.000
25%,5516.000,1253.000,55.601,37.372,5.000,5.000,3210.000,54.000,21.000,14.000,...,11.000,10.000,60.600,2.000,1.500,5.000,1.000,1.000,6610.000,587495119.500
50%,8546.000,1787.000,55.730,37.544,13.000,15.000,9042.000,165.000,65.000,52.000,...,26.000,26.000,105.300,3.000,3.000,7.000,2.000,1.000,12234.000,1615577310.000
75%,13683.000,4774.000,55.846,37.741,18.000,20.000,16535.000,315.000,146.000,114.000,...,58.100,79.750,183.000,5.000,4.000,10.000,4.000,2.000,20006.500,3235660609.000
max,19925.000,7698.000,60.059,39.542,95.000,95.000,141350.000,2677.000,2314.000,1254.000,...,860.000,1000.000,2876.000,76.000,32.000,878.000,51.000,13.000,130546.000,41899645000.000

#### 2.1.2 ПРЕДОБРАБОТКА

In [ ]:
# Очистка столбца 'ID' от некорректных данных
df_grouped['ID'] = df_grouped['ID'].str.replace(r'[^\d]', '', regex=True) # Удалить все нецифровые символы
df_grouped = df_grouped[df_grouped['ID'] != ''] # Удалить пустые строки

# Приведение типа с заменой NaN на 0
df_grouped['ID'] = df_grouped['ID'].replace('', float('nan')) # Заменить пустые строки на NaN
df_grouped['ID'] = df_grouped['ID'].astype(float).fillna(0).astype(int) # Приведение типа к int

In [ ]:
new_building_1 = new_building.copy()
new_building_1['ID']=new_building_1['ID ЖК']

new_building_1.info()

new_building_1 = new_building_1.groupby('ID').agg(lambda x: x.iloc[0] if isinstance(x, pd.Series) else x).reset_index()

new_building_1 = new_building_1.drop(columns=['ID К','кр Корпус','Корпус', 'Адрес корп', 'АТД', 'Округ Направление', 'Валюта цены в К', 'Очередь', 'РВЭ', 'ст', 'Продано кв и ап розн', 'Остатки кв и ап в розн',	'% остатков в лотах',	'Кв и ап. в прайсах',	'Участок',	'Продано кв и ап розн кв. м',	'Остатки кв и ап в розн кв. м',	'% остатков в кв. м',	'Продажи кв и ап розн в месяц кв. м',	'Продажи кв и ап розн в месяц',	'мес. для продажи',		'изменение ср. цены кв. м',	'номер ПД и объекта',	'м/м на придомовой территории (д)',	'м/м вне придомовой территории (д)',	'м/м в паркинге (д)'])

merged_df = pd.merge( new_building_1, df_grouped, on='ID',  how='inner')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11957 entries, 0 to 11956
Data columns (total 75 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ID К                                     11957 non-null  int64
 1   ID ЖК                                    11957 non-null  int64
 2   ЖК рус                                   11957 non-null  object
 3   ЖК англ                                  3323 non-null   object
 4   Корпус                                   11957 non-null  object
 5   кр Корпус                                11948 non-null  object
 6   Адрес корп                               11957 non-null  object
 7   lat                                      11957 non-null  float64
 8   lng                                      11957 non-null  float64
 9   Район Город                              11957 non-null  object
 10  Округ Направление                        11957 non-null  object
 11  Регион                                   11957 non-null  object
 12  АТД                                      11957 non-null  object
 13  Метро                                    11563 non-null  object
 14  Станция жд                               4474 non-null   object
 15  Застройщик ЖК                            11957 non-null  object
 16  Этажность К мин                          11957 non-null  int64
 17  Этажность К макс                         11957 non-null  int64
 18  Площадь К                                11957 non-null  int64
 19  Квартир в К                              11957 non-null  int64
 20  1к кв                                    11957 non-null  int64
 21  2к кв                                    11957 non-null  int64
 22  3к кв                                    11957 non-null  int64
 23  4к кв                                    11957 non-null  int64
 24  Тип помещений                            11957 non-null  object
 25  Стены в К                                11957 non-null  object
 26  Сдача К                                  11955 non-null  object
 27  Стадия К                                 11957 non-null  object
 28  Старт продаж К                           10897 non-null  float64
 29  Договор К                                11957 non-null  object
 30  Валюта цены в К                          9913 non-null   object
 31  Класс К                                  11957 non-null  object
 32  до МКАД                                  11957 non-null  float64
 33  внутри                                   11957 non-null  int64
 34  Отделка                                  11956 non-null  object
 35  Зона                                     11957 non-null  object
 36  Очередь                                  10341 non-null  object
 37  РВЭ                                      4824 non-null   object
 38  ст                                       1911 non-null   float64
 39  Метро транспортом                        11957 non-null  int64
 40  Метро пешком                             11957 non-null  int64
 41  Высота потолков                          7433 non-null   object
 42  Продано кв и ап розн                     11957 non-null  int64
 43  Остатки кв и ап в розн                   11957 non-null  int64
 44  % остатков в лотах                       11957 non-null  float64
 45  Кв и ап. в прайсах                       11957 non-null  int64
 46  % расп. корпусов                         11957 non-null  float64
 47  Участок                                  10819 non-null  object
 48  Продано кв и ап розн кв. м               11957 non-null  int64
 49  Остатки кв и ап в розн кв. м             11957 non-null  int64
 50  % остатков в кв. м                       11957 non-null  float64
 51  Продажи кв и ап розн в месяц кв. м       11957 non-null  float64
 52  Продажи кв и ап розн в месяц             11957 non-null  float64
 53  мес. для продажи                         11957 non-null  float64
 54  мес. до сдачи                            11957 non-null  int64
 55  срок экспозиции, мес                     11957 non-null  int64
 56  изменение ср. цены кв. м                 11957 non-null  float64
 57  среднемес рост цен                       11957 non-null  float64
 58  номер ПД и объекта                       7058 non-null   object
 59  ID дом.рф                                6507 non-null   float64
 60  Ключи (д)                                4768 non-null   object
 61  Дата РВЭ (д)                             4127 non-null   object
 62  м/м на придомовой территории (д)         3855 non-null   float64
 63  м/м вне придомовой территории (д)        2194 non-null   float64
 64  м/м в паркинге (д)                       2627 non-null   float64
 65  пассажирских лифтов (д)                  3557 non-null   float64
 66  грузовых лифтов (д)                      2000 non-null   float64
 67  квартир на площадке (д)                  5580 non-null   float64
 68  подъездов (д)                            5580 non-null   float64
 69  корпусов в объекте                       6499 non-null   float64
 70  Общая площадь (д)                        3156 non-null   float64
 71  Планируемая стоимость строительства (д)  3227 non-null   float64
 72  Банк эскроу (д)                          2676 non-null   object
 73  Банк кредитор (д)                        2676 non-null   object
 74  ID                                       11957 non-null  int64
dtypes: float64(24), int64(21), object(30)
memory usage: 6.8+ MB

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101475 entries, 0 to 101474
Data columns (total 58 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   ID                                       101475 non-null  int64
 1   ID ЖК                                    101475 non-null  int64
 2   ЖК рус                                   101475 non-null  object
 3   ЖК англ                                  33881 non-null   object
 4   lat                                      101475 non-null  float64
 5   lng                                      101475 non-null  float64
 6   Район Город                              101475 non-null  object
 7   Регион                                   101475 non-null  object
 8   Метро                                    97507 non-null   object
 9   Станция жд                               37732 non-null   object
 10  Застройщик ЖК                            101475 non-null  object
 11  Этажность К мин                          101475 non-null  int64
 12  Этажность К макс                         101475 non-null  int64
 13  Площадь К                                101475 non-null  int64
 14  Квартир в К                              101475 non-null  int64
 15  1к кв                                    101475 non-null  int64
 16  2к кв                                    101475 non-null  int64
 17  3к кв                                    101475 non-null  int64
 18  4к кв                                    101475 non-null  int64
 19  Тип помещений                            101475 non-null  object
 20  Стены в К                                101475 non-null  object
 21  Сдача К                                  101475 non-null  object
 22  Стадия К                                 101475 non-null  object
 23  Старт продаж К                           100283 non-null  float64
 24  Договор К                                101475 non-null  object
 25  Класс К                                  101475 non-null  object
 26  до МКАД                                  101475 non-null  float64
 27  внутри                                   101475 non-null  int64
 28  Отделка                                  101475 non-null  object
 29  Зона                                     101475 non-null  object
 30  Метро транспортом                        101475 non-null  int64
 31  Метро пешком                             101475 non-null  int64
 32  Высота потолков                          87884 non-null   object
 33  % расп. корпусов                         101475 non-null  float64
 34  мес. до сдачи                            101475 non-null  int64
 35  срок экспозиции, мес                     101475 non-null  int64
 36  среднемес рост цен                       101475 non-null  float64
 37  ID дом.рф                                81873 non-null   float64
 38  Ключи (д)                                58809 non-null   object
 39  Дата РВЭ (д)                             69551 non-null   object
 40  пассажирских лифтов (д)                  44368 non-null   float64
 41  грузовых лифтов (д)                      26647 non-null   float64
 42  квартир на площадке (д)                  73328 non-null   float64
 43  подъездов (д)                            73328 non-null   float64
 44  корпусов в объекте                       81857 non-null   float64
 45  Общая площадь (д)                        34958 non-null   float64
 46  Планируемая стоимость строительства (д)  35408 non-null   float64
 47  Банк эскроу (д)                          22034 non-null   object
 48  Банк кредитор (д)                        22034 non-null   object
 49  project                                  101475 non-null  object
 50  year                                     101475 non-null  int64
 51  months                                   101475 non-null  int64
 52  developer                                101475 non-null  object
 53  region                                   101475 non-null  object
 54  okrug                                    101475 non-null  object
 55  corpus                                   101475 non-null  object
 56  price                                    101475 non-null  float64
 57  sales_live                               101475 non-null  float64
dtypes: float64(16), int64(17), object(25)
memory usage: 44.9+ MB

In [ ]:
print("Уникальные значения в колонке 'Старт продаж К':")
print(merged_df['Старт продаж К'].unique())

Уникальные значения в колонке 'Старт продаж К':
[2013.6  2011.2  2012.1  2010.12 2011.7  2012.9  2012.5  2012.8  2012.12
 2013.4  2010.8  2012.7  2012.6  2014.2  2014.3  2013.11 2014.4  2013.7
 2013.2  2013.3  2015.4  2011.1  2014.1  2011.11 2010.3  2012.2  2012.11
 2013.12 2014.7  2013.9  2013.1  2011.3  2011.8  2010.1  2013.8  2014.5
 2015.7  2014.11 2016.1  2014.9  2016.2  2014.8  2016.3  2014.6  2015.1
 2014.12 2015.2  2015.3  2015.5  2019.11 2015.9  2015.8  2015.6  2015.11
 2015.12 2016.4  2016.5  2016.6  2018.2  2016.7  2016.8  2016.9  2016.11
 2016.12 2017.1  2017.2  2017.3  2017.4  2017.5  2017.6  2017.7  2017.8
 2017.9  2017.11 2017.12 2024.7  2018.1  2018.3  2018.4  2018.7  2018.5
 2018.6  2019.1  2018.8  2020.1  2018.9  2019.2  2018.11 2018.12 2019.3
 2019.9  2020.9  2019.12 2019.4  2020.8  2019.5      nan 2019.6  2019.7
 2022.6  2019.8  2020.4  2021.2  2023.11 2020.2  2020.11 2021.9  2020.5
 2020.3  2020.6  2021.3  2021.8  2020.7  2020.12 2022.5  2021.1  2021.4
 2021.6  2021.12 2021.11 2021.5  2021.7  2022.3  2023.1  2022.11 2022.8
 2022.7  2022.1  2023.6  2022.4  2022.2  2022.12 2022.9  2023.5  2023.4
 2023.7  2023.2  2023.12 2023.8  2024.8  2024.4  2024.1  2023.9  2024.5
 2024.2  2024.3  2024.6 ]

In [ ]:
# Функция для преобразования float в даты
def convert_to_date(float_date):
    try:
    # Преобразуем float в строку и разделяем на год и месяц
        year = int(str(float_date).split('.')[0])
        month = int(str(float_date).split('.')[1])
        return pd.to_datetime(f"{year}-{month}-01")

    except Exception as e:
        return pd.NaT # В случае ошибки возвращаем NaT

In [ ]:
# Применяем функцию к колонке [Старт продаж К]
merged_df['Старт продаж К'] = merged_df['Старт продаж К'].apply(convert_to_date)

In [ ]:
# Группировка и получение минимумов
min_dates = merged_df.groupby('ID ЖК')['Старт продаж К'].min().reset_index()

In [ ]:
# Переименование колонки
min_dates.rename(columns={'Старт продаж К': 'min дата РНС'}, inplace=True)

In [ ]:
# Объединение с исходным датафреймом
merged_df = merged_df.merge(min_dates, on='ID ЖК', how='left')

In [ ]:
def convert_quarter_to_date(quarter_str):
    quarter, year = quarter_str.split(' кв ')
    month = (int(quarter) - 1) * 3 + 1  # Преобразование квартала в месяц
    return pd.Timestamp(year=int(year), month=month, day=1)

In [ ]:
# Преобразуем колонку 'Сдача К' в стандартный формат
merged_df['Сдача К'] = merged_df['Сдача К'].apply(convert_quarter_to_date)

In [ ]:
# Находим максимальную дату для каждого ID ЖК
merged_df['max дата РНВ'] = merged_df.groupby('ID ЖК')['Сдача К'].transform('max')

In [ ]:
# Сортируем данные
merged_df_sorted = merged_df.sort_values(['project', 'year', 'months'])

# Рассчитываем месячный рост цен
merged_df_sorted['monthly_growth'] = merged_df_sorted.groupby('project')['sales_live'].transform(
    lambda x: (x / x.shift(1)) - 1)

# Создаем кумулятивную сумму роста для каждого project
merged_df_sorted['cumsum_growth'] = merged_df_sorted.groupby('project')['monthly_growth'].cumsum()

# Считаем количество периодов для каждого project
merged_df_sorted['periods'] = merged_df_sorted.groupby('project').cumcount()

# Рассчитываем среднее значение роста (кумулятивная сумма / количество периодов)
merged_df_sorted['average_price_growth'] = merged_df_sorted['cumsum_growth'] / merged_df_sorted['periods'].replace(0, 1)

 #Добавляем результат в исходный датафрейм
merged_df['average_price_growth'] = merged_df_sorted['average_price_growth']

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101475 entries, 0 to 101474
Data columns (total 61 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   ID                                       101475 non-null  int64
 1   ID ЖК                                    101475 non-null  int64
 2   ЖК рус                                   101475 non-null  object
 3   ЖК англ                                  33881 non-null   object
 4   lat                                      101475 non-null  float64
 5   lng                                      101475 non-null  float64
 6   Район Город                              101475 non-null  object
 7   Регион                                   101475 non-null  object
 8   Метро                                    97507 non-null   object
 9   Станция жд                               37732 non-null   object
 10  Застройщик ЖК                            101475 non-null  object
 11  Этажность К мин                          101475 non-null  int64
 12  Этажность К макс                         101475 non-null  int64
 13  Площадь К                                101475 non-null  int64
 14  Квартир в К                              101475 non-null  int64
 15  1к кв                                    101475 non-null  int64
 16  2к кв                                    101475 non-null  int64
 17  3к кв                                    101475 non-null  int64
 18  4к кв                                    101475 non-null  int64
 19  Тип помещений                            101475 non-null  object
 20  Стены в К                                101475 non-null  object
 21  Сдача К                                  101475 non-null  datetime64[ns]
 22  Стадия К                                 101475 non-null  object
 23  Старт продаж К                           100283 non-null  datetime64[ns]
 24  Договор К                                101475 non-null  object
 25  Класс К                                  101475 non-null  object
 26  до МКАД                                  101475 non-null  float64
 27  внутри                                   101475 non-null  int64
 28  Отделка                                  101475 non-null  object
 29  Зона                                     101475 non-null  object
 30  Метро транспортом                        101475 non-null  int64
 31  Метро пешком                             101475 non-null  int64
 32  Высота потолков                          87884 non-null   object
 33  % расп. корпусов                         101475 non-null  float64
 34  мес. до сдачи                            101475 non-null  int64
 35  срок экспозиции, мес                     101475 non-null  int64
 36  среднемес рост цен                       101475 non-null  float64
 37  ID дом.рф                                81873 non-null   float64
 38  Ключи (д)                                58809 non-null   object
 39  Дата РВЭ (д)                             69551 non-null   object
 40  пассажирских лифтов (д)                  44368 non-null   float64
 41  грузовых лифтов (д)                      26647 non-null   float64
 42  квартир на площадке (д)                  73328 non-null   float64
 43  подъездов (д)                            73328 non-null   float64
 44  корпусов в объекте                       81857 non-null   float64
 45  Общая площадь (д)                        34958 non-null   float64
 46  Планируемая стоимость строительства (д)  35408 non-null   float64
 47  Банк эскроу (д)                          22034 non-null   object
 48  Банк кредитор (д)                        22034 non-null   object
 49  project                                  101475 non-null  object
 50  year                                     101475 non-null  int64
 51  months                                   101475 non-null  int64
 52  developer                                101475 non-null  object
 53  region                                   101475 non-null  object
 54  okrug                                    101475 non-null  object
 55  corpus                                   101475 non-null  object
 56  price                                    101475 non-null  float64
 57  sales_live                               101475 non-null  float64
 58  min дата РНС                             100283 non-null  datetime64[ns]
 59  max дата РНВ                             101475 non-null  datetime64[ns]
 60  average_price_growth                     31868 non-null   float64
dtypes: datetime64[ns](4), float64(16), int64(17), object(24)
memory usage: 47.2+ MB

In [ ]:
df_grouped_new = df_grouped  # Исправленный вызов функции
df_grouped_new_agg = df_grouped_new.groupby(['project']).agg({'sales_live': 'sum'}).sort_values('sales_live', ascending=False).reset_index()

In [ ]:
df_grouped_old = test_declarations.groupby(['ЖК']).agg({'Продано квартир (кв. м.)': 'sum'}).sort_values('Продано квартир (кв. м.)', ascending=False).reset_index()
df_grouped_old

                        ЖК  Продано квартир (кв. м.)
0          Пригород Лесное                722512.000
1           Саларьево Парк                697826.000
2          Люблинский парк                604134.000
3                   Символ                552815.000
4                 Прокшино                486354.000
...                    ...                       ...
1013  Сокольнический вал 1                     0.000
1014            Соле Хиллс                     0.000
1015         Солнцево Парк                     0.000
1016             Сохо Нохо                     0.000
1017                Вэллби                     0.000

[1018 rows x 2 columns]

In [ ]:
print(sum(df_grouped_new['sales_live']))
print(sum(df_grouped_old['Продано квартир (кв. м.)']))

48064372.00000076
48064372.0